/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_smarthome_activityrecognition_jni_ActivityRecognizer */

#ifndef _Included_org_smarthome_activityrecognition_jni_ActivityRecognizer
#define _Included_org_smarthome_activityrecognition_jni_ActivityRecognizer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_smarthome_activityrecognition_jni_ActivityRecognizer
 * Method:    create
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_smarthome_activityrecognition_jni_ActivityRecognizer_create
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_smarthome_activityrecognition_jni_ActivityRecognizer
 * Method:    clean
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_smarthome_activityrecognition_jni_ActivityRecognizer_clean
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_smarthome_activityrecognition_jni_ActivityRecognizer
 * Method:    readConfiguration
 * Signature: (ILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_smarthome_activityrecognition_jni_ActivityRecognizer_readConfiguration
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     org_smarthome_activityrecognition_jni_ActivityRecognizer
 * Method:    setConfiguration
 * Signature: (ILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_smarthome_activityrecognition_jni_ActivityRecognizer_setConfiguration
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     org_smarthome_activityrecognition_jni_ActivityRecognizer
 * Method:    trainSVM
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_smarthome_activityrecognition_jni_ActivityRecognizer_trainSVM__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_smarthome_activityrecognition_jni_ActivityRecognizer
 * Method:    trainSVM
 * Signature: (ILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_smarthome_activityrecognition_jni_ActivityRecognizer_trainSVM__ILjava_lang_String_2
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     org_smarthome_activityrecognition_jni_ActivityRecognizer
 * Method:    testSVM
 * Signature: (ILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_smarthome_activityrecognition_jni_ActivityRecognizer_testSVM
  (JNIEnv *, jobject, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
